# Generated by Django 5.1.6 on 2025-02-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_otp',
            new_name='email_otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_verified',
        ),
    ]
