# Generated by Django 5.1.6 on 2025-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
