# Generated by Django 5.1.6 on 2025-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zip_code',
            new_name='pincode',
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.TextField(),
        ),
    ]
